name: Update documentation

on:
  push:
    branches: [ main ]

jobs:
  update_documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update documentation
      env:
        API_ENDPOINT: https://jens.vandewiel.eu # Replace with your API endpoint
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        for file in $(find . -type f -name "*.md"); do
          content=$(cat "$file")
          name=${file#./}
          request="{\"name\": \"$name\", \"content\": \"$content\"}"
          echo "API request: curl -X POST $API_ENDPOINT/api/document/update/$name -H \"Authorization: Bearer $API_TOKEN\" -H \"Content-Type: application/json\" -d '$request'"
          curl -X POST $API_ENDPOINT/api/document/update/$name \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$request"
        done
