name: Upload docs

on:
  push:
    branches:
      - main

jobs:
  sync_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve file list
        run: |
          printf '%s\n' $(find . -name "*.md") >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Upload files to API
        env:
          TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          while read -r file; do
            file_name=$(basename "$file")
            file_content=$(cat "$file")
            echo "${file_name}=${file_content}" >> $GITHUB_STATE
            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d '{"name":"'$file_name'","content":"'$file_content'"}' https://jens.vandewiel.eu/api/document/update/"$file_name")
            echo "$file_name: $response"
          done < "$GITHUB_OUTPUT"
