name: Update documentation

on:
  push:
    branches: [ main ]

jobs:
  update_documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update documentation
      env:
        API_ENDPOINT: https://jens.vandewiel.eu # Replace with your API endpoint
        API_TOKEN: ${{ secrets.API_TOKEN }}
        IGNORE_FILES: "README.md" # Set ignored files here, separated by space
      run: |
        ignore_files=($IGNORE_FILES)
        for file in $(find . -type f -name "*.md"); do
          file_name=$(basename "$file")
          if [[ " ${ignore_files[@]} " =~ " $file_name " ]]; then
            continue
          fi
          content=$(cat "$file")
          name=${file#./}
          name=${name%.md}
          request="{\"name\": \"$name\", \"content\": \"$content\"}"
          echo "API request: curl -X POST $API_ENDPOINT/api/document/update/$name -H \"Authorization: Bearer $API_TOKEN\" -H \"Content-Type: application/json\" -d '$request'"
          curl -X POST $API_ENDPOINT/api/document/update/$name \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$request"
        done
